name: Android Dev Github Action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the staging branch
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Set up Flutter.
      - name: Clone Flutter repository with beta channel
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: beta

      # Set up Android dependencies
      - name: Install Android dependencies
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - run: flutter doctor -v

      # Checkout code and get packages
      - name: Checkout source code
        uses: actions/checkout@v2

      - run: flutter pub get

      # Build apk.
      - run: flutter build apk

      # Upload generated apk to the artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: pre-release-testers
          releaseNotesFile: ReleaseNotes.txt
          file: build/app/outputs/apk/release/app-release.apk